// packages/vue/src/GriddleGrid.vue
<template>
  <div
    ref="scrollEl"
    :class="className"
    :style="scrollStyle"
    @pointerdown="onBackgroundPointerDown"
  >
    <div :style="contentStyle">
      <div
        v-if="indicatorRect"
        class="griddle-drop-indicator"
        :style="{
          position: 'absolute',
          left: indicatorRect.left + 'px',
          top: indicatorRect.top + 'px',
          width: indicatorRect.width + 'px',
          height: indicatorRect.height + 'px',
          boxSizing: 'border-box',
          border: '2px dashed rgba(59, 91, 219, 0.55)',
          background: 'rgba(59, 91, 219, 0.08)',
          borderRadius: (config.tileRadius ?? 4) + 'px',
          pointerEvents: 'none',
          zIndex: 5,
        }"
      ></div>
      <div
        v-if="drawGhostRect"
        class="griddle-draw-ghost"
        :style="{
          position: 'absolute',
          left: drawGhostRect.left + 'px',
          top: drawGhostRect.top + 'px',
          width: drawGhostRect.width + 'px',
          height: drawGhostRect.height + 'px',
          boxSizing: 'border-box',
          border: '2px dashed rgba(59, 91, 219, 0.55)',
          background: 'rgba(59, 91, 219, 0.08)',
          borderRadius: (config.tileRadius ?? 4) + 'px',
          pointerEvents: 'none',
          zIndex: 5,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: '14px',
          fontWeight: '600',
          color: 'rgba(59, 91, 219, 0.8)',
          userSelect: 'none',
        }"
      >{{ drawGhostRect.label }}</div>
      <div
        v-for="tile in rendered"
        :key="tile.id"
        :data-griddle-tile="tile.id"
        :class="['griddle-tile', {
          'griddle-dragging': drag?.tileId === tile.id || pinDrag?.tileId === tile.id || (groupDrag !== null && groupDragSet.has(tile.id)),
          'griddle-resizing': resize?.tileId === tile.id,
          'griddle-selected': selection.has(tile.id),
        }]"
        :style="tileStyle(tile)"
        @pointerdown="(e) => onTilePointerDown(e, tile)"
        :ref="(el) => registerNode(tile.id, el as HTMLDivElement | null)"
      >
        <slot name="tile" :tile="tile" :selected="selection.has(tile.id)" />
        <template v-if="tile.resizable !== false">
          <div
            v-for="c in (tile.resizeHandles ?? config.resizeHandles ?? ['se'])"
            :key="c"
            :data-griddle-handle="c"
            :style="handleStyle(c)"
            @pointerdown="(e) => onResizeHandleDown(e, tile, c)"
          ></div>
        </template>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch, nextTick } from 'vue';
import type { Corner, Tile } from '@griddle/core';
import {
  visibleRange,
  visibleTiles,
  gridContentSize,
  DragController,
  GroupDragController,
  computeTileLayout,
  resolveStickyStacking,
  isOutOfFlow,
  pixelsToPin,
} from '@griddle/core';
import type { TileLayout } from '@griddle/core';
import type { GriddleApi } from './useGriddle.js';

const props = defineProps<{
  api: GriddleApi;
  className?: string;
  height?: number | string;
  showGrid?: boolean;
  /** Controlled selection. If omitted, managed internally. */
  selection?: Set<string>;
}>();

const emit = defineEmits<{
  (e: 'selectionChange', selection: Set<string>): void;
  (e: 'drawCreate', rect: { col: number; row: number; w: number; h: number }): void;
}>();

const scrollEl = ref<HTMLDivElement | null>(null);
const viewport = ref({ scrollX: 0, scrollY: 0, width: 1000, height: 800 });

const config = computed(() => props.api.config.value);
const gap = computed(() => config.value.gap ?? 0);
const halfGap = computed(() => gap.value / 2);
const colSize = computed(() => config.value.unitWidth + gap.value);
const rowSize = computed(() => config.value.unitHeight + gap.value);

const range = computed(() => visibleRange(config.value, viewport.value, 4));
const rendered = computed(() => visibleTiles(props.api.tiles.value, range.value));
const contentSize = computed(() => gridContentSize(config.value, props.api.tiles.value));

const scrollStyle = computed(() => ({
  position: 'relative' as const,
  overflow: 'auto' as const,
  height: props.height ?? '100%',
  touchAction: 'none' as const,
}));

const contentStyle = computed(() => {
  const showGrid = props.showGrid !== false;
  const bg = showGrid
    ? {
        backgroundImage: `linear-gradient(to right, rgba(0,0,0,0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,0,0,0.08) 1px, transparent 1px)`,
        backgroundSize: `${colSize.value}px ${rowSize.value}px`,
      }
    : {};
  return {
    position: 'relative' as const,
    width: contentSize.value.width || '100%',
    height: contentSize.value.height || '100%',
    minWidth: '100%',
    minHeight: '100%',
    // Expose tile radius as a CSS variable so user tile content can pick it up.
    ['--griddle-tile-radius' as string]: (config.value.tileRadius ?? 4) + 'px',
    ...bg,
  };
});

// Selection state
const internalSelection = ref<Set<string>>(new Set());
const selection = computed(() => props.selection ?? internalSelection.value);
const groupDragSet = computed(() => new Set(groupDrag.value?.tileIds ?? []));
function setSelection(next: Set<string>) {
  if (!props.selection) internalSelection.value = next;
  emit('selectionChange', next);
}

const dragController = new DragController(props.api.grid);
const groupDragController = new GroupDragController(props.api.grid);

interface DragVisual {
  tileId: string;
  pickupCol: number;
  pickupRow: number;
  deltaX: number;
  deltaY: number;
  indicatorCol: number | null;
  indicatorRow: number | null;
}
const drag = ref<DragVisual | null>(null);
let dragStartPointerX = 0;
let dragStartPointerY = 0;

interface GroupDragVisual {
  tileIds: string[];
  deltaX: number;
  deltaY: number;
  committedDcol: number;
  committedDrow: number;
}
const groupDrag = ref<GroupDragVisual | null>(null);

interface PinDragState {
  tileId: string;
  startPinPx: { x: number; y: number };
  startPointerX: number;
  startPointerY: number;
}
const pinDrag = ref<PinDragState | null>(null);

interface ResizeState {
  tileId: string;
  corner: Corner;
  startPointerX: number;
  startPointerY: number;
  startW: number;
  startH: number;
  startCol: number;
  startRow: number;
  previewW: number;
  previewH: number;
  previewCol: number;
  previewRow: number;
}
const resize = ref<ResizeState | null>(null);

interface DrawState {
  anchorCol: number;
  anchorRow: number;
  currentCol: number;
  currentRow: number;
}
const drawState = ref<DrawState | null>(null);

function onTilePointerDown(e: PointerEvent, tile: Tile) {
  if (tile.draggable === false) return;
  if ((e.target as HTMLElement).dataset.griddleHandle) return;

  const metaKey = e.metaKey || e.ctrlKey;

  // Out-of-flow tiles get free-pixel drag (no selection).
  if (config.value.enablePositioning && isOutOfFlow(tile)) {
    (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
    const layout = computeTileLayout({
      tile,
      config: config.value,
      scrollX: viewport.value.scrollX,
      scrollY: viewport.value.scrollY,
      viewportWidth: viewport.value.width,
      viewportHeight: viewport.value.height,
    });
    const startPinPx =
      tile.position === 'fixed'
        ? { x: layout.left - viewport.value.scrollX, y: layout.top - viewport.value.scrollY }
        : { x: layout.left, y: layout.top };
    pinDrag.value = {
      tileId: tile.id,
      startPinPx,
      startPointerX: e.clientX,
      startPointerY: e.clientY,
    };
    e.stopPropagation();
    return;
  }

  // Cmd/Ctrl+click toggles selection without starting a drag.
  if (metaKey) {
    e.preventDefault();
    const next = new Set(selection.value);
    if (next.has(tile.id)) {
      next.delete(tile.id);
    } else {
      next.add(tile.id);
    }
    setSelection(next);
    e.stopPropagation();
    return;
  }

  const tileIsSelected = selection.value.has(tile.id);

  if (!tileIsSelected) {
    setSelection(new Set([tile.id]));
  }

  // Capture pointer only when starting a drag.
  (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);

  // Group drag if 2+ tiles selected including this one.
  const effectiveSelection = tileIsSelected ? selection.value : new Set([tile.id]);
  if (effectiveSelection.size > 1) {
    const ids = Array.from(effectiveSelection);
    if (!groupDragController.start(ids)) return;
    dragStartPointerX = e.clientX;
    dragStartPointerY = e.clientY;
    groupDrag.value = {
      tileIds: ids,
      deltaX: 0,
      deltaY: 0,
      committedDcol: 0,
      committedDrow: 0,
    };
    e.stopPropagation();
    return;
  }

  // Single tile drag.
  if (!dragController.start(tile.id)) return;
  dragStartPointerX = e.clientX;
  dragStartPointerY = e.clientY;
  drag.value = {
    tileId: tile.id,
    pickupCol: tile.col,
    pickupRow: tile.row,
    deltaX: 0,
    deltaY: 0,
    indicatorCol: tile.col,
    indicatorRow: tile.row,
  };
  e.stopPropagation();
}

function onBackgroundPointerDown(e: PointerEvent) {
  if ((e.target as HTMLElement).closest('[data-griddle-tile]')) return;
  setSelection(new Set());

  const el = scrollEl.value;
  if (!el) return;
  const rect = el.getBoundingClientRect();
  const x = e.clientX - rect.left + el.scrollLeft;
  const y = e.clientY - rect.top + el.scrollTop;
  const col = Math.floor(x / colSize.value);
  const row = Math.floor(y / rowSize.value);
  drawState.value = { anchorCol: col, anchorRow: row, currentCol: col, currentRow: row };
  (el as HTMLDivElement).setPointerCapture(e.pointerId);
}

function onResizeHandleDown(e: PointerEvent, tile: Tile, c: Corner) {
  if (tile.resizable === false) return;
  (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
  resize.value = {
    tileId: tile.id,
    corner: c,
    startPointerX: e.clientX,
    startPointerY: e.clientY,
    startW: tile.w,
    startH: tile.h,
    startCol: tile.col,
    startRow: tile.row,
    previewW: tile.w,
    previewH: tile.h,
    previewCol: tile.col,
    previewRow: tile.row,
  };
  e.stopPropagation();
}

function onPointerMove(e: PointerEvent) {
  if (drawState.value) {
    const el = scrollEl.value;
    if (el) {
      const rect = el.getBoundingClientRect();
      const x = e.clientX - rect.left + el.scrollLeft;
      const y = e.clientY - rect.top + el.scrollTop;
      const col = Math.max(0, Math.floor(x / colSize.value));
      const row = Math.max(0, Math.floor(y / rowSize.value));
      drawState.value = { ...drawState.value, currentCol: col, currentRow: row };
    }
    return;
  }
  const pd = pinDrag.value;
  const gd = groupDrag.value;
  const d = drag.value;
  const r = resize.value;
  if (pd) {
    const dx = e.clientX - pd.startPointerX;
    const dy = e.clientY - pd.startPointerY;
    const newPinPx = { x: pd.startPinPx.x + dx, y: pd.startPinPx.y + dy };
    const newPin = pixelsToPin(newPinPx, config.value);
    props.api.grid.setTilePinned(pd.tileId, newPin);
  }
  if (gd) {
    const dx = e.clientX - dragStartPointerX;
    const dy = e.clientY - dragStartPointerY;
    const dcol = Math.round(dx / colSize.value);
    const drow = Math.round(dy / rowSize.value);
    const result = groupDragController.update({ dcol, drow });
    groupDrag.value = {
      ...gd,
      deltaX: dx,
      deltaY: dy,
      committedDcol: result.indicatorDelta?.dcol ?? gd.committedDcol,
      committedDrow: result.indicatorDelta?.drow ?? gd.committedDrow,
    };
  }
  if (d) {
    const dx = e.clientX - dragStartPointerX;
    const dy = e.clientY - dragStartPointerY;
    const candidateCol = d.pickupCol + Math.round(dx / colSize.value);
    const candidateRow = d.pickupRow + Math.round(dy / rowSize.value);
    const result = dragController.update({ col: candidateCol, row: candidateRow });
    drag.value = {
      ...d,
      deltaX: dx,
      deltaY: dy,
      indicatorCol: result.indicatorCell ? result.indicatorCell.col : null,
      indicatorRow: result.indicatorCell ? result.indicatorCell.row : null,
    };
  }
  if (r) {
    const dx = e.clientX - r.startPointerX;
    const dy = e.clientY - r.startPointerY;
    let dw = 0, dh = 0, dcol = 0, drow = 0;
    const stepsX = Math.round(dx / colSize.value);
    const stepsY = Math.round(dy / rowSize.value);
    if (r.corner === 'se' || r.corner === 'ne') dw = stepsX;
    if (r.corner === 'se' || r.corner === 'sw') dh = stepsY;
    if (r.corner === 'sw' || r.corner === 'nw') { dw = -stepsX; dcol = stepsX; }
    if (r.corner === 'ne' || r.corner === 'nw') { dh = -stepsY; drow = stepsY; }
    const nW = Math.max(1, r.startW + dw);
    const nH = Math.max(1, r.startH + dh);
    const nC = r.startCol + dcol;
    const nR = r.startRow + drow;
    if (nW !== r.previewW || nH !== r.previewH || nC !== r.previewCol || nR !== r.previewRow) {
      resize.value = { ...r, previewW: nW, previewH: nH, previewCol: nC, previewRow: nR };
    }
  }
}

function syncTiles() {
  // DragController/GroupDragController may restore grid snapshots without
  // emitting change events. Force-sync the reactive tiles ref so the UI
  // reflects the grid's true state after a drag ends.
  props.api.tiles.value = props.api.grid.tiles;
  props.api.version.value++;
}

function onPointerUp() {
  if (drawState.value) {
    const ds = drawState.value;
    const col = Math.min(ds.anchorCol, ds.currentCol);
    const row = Math.min(ds.anchorRow, ds.currentRow);
    const w = Math.max(1, Math.abs(ds.currentCol - ds.anchorCol) + 1);
    const h = Math.max(1, Math.abs(ds.currentRow - ds.anchorRow) + 1);
    drawState.value = null;
    emit('drawCreate', { col, row, w, h });
    return;
  }
  if (pinDrag.value) {
    pinDrag.value = null;
  }
  if (groupDrag.value) {
    groupDragController.end();
    groupDrag.value = null;
    syncTiles();
  }
  if (drag.value) {
    dragController.end();
    drag.value = null;
    syncTiles();
  }
  const r = resize.value;
  if (r) {
    const t = props.api.grid.getTile(r.tileId);
    if (t) {
      if (r.previewCol !== t.col || r.previewRow !== t.row) {
        props.api.moveTile(r.tileId, { col: r.previewCol, row: r.previewRow });
      }
      if (r.previewW !== t.w || r.previewH !== t.h) {
        props.api.resizeTile(r.tileId, { w: r.previewW, h: r.previewH });
      }
    }
    resize.value = null;
  }
}

function updateViewport() {
  const el = scrollEl.value;
  if (!el) return;
  viewport.value = {
    scrollX: el.scrollLeft,
    scrollY: el.scrollTop,
    width: el.clientWidth,
    height: el.clientHeight,
  };
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape') setSelection(new Set());
}

let ro: ResizeObserver | null = null;
onMounted(() => {
  updateViewport();
  const el = scrollEl.value!;
  el.addEventListener('scroll', updateViewport, { passive: true });
  ro = new ResizeObserver(updateViewport);
  ro.observe(el);
  window.addEventListener('pointermove', onPointerMove);
  window.addEventListener('pointerup', onPointerUp);
  window.addEventListener('pointercancel', onPointerUp);
  window.addEventListener('keydown', onKeyDown);
});
onBeforeUnmount(() => {
  const el = scrollEl.value;
  if (el) el.removeEventListener('scroll', updateViewport);
  ro?.disconnect();
  window.removeEventListener('pointermove', onPointerMove);
  window.removeEventListener('pointerup', onPointerUp);
  window.removeEventListener('pointercancel', onPointerUp);
  window.removeEventListener('keydown', onKeyDown);
});

const tileNodes = new Map<string, HTMLDivElement>();
const prevRects = new Map<string, { x: number; y: number }>();
function registerNode(id: string, el: HTMLDivElement | null) {
  if (el) tileNodes.set(id, el);
  else tileNodes.delete(id);
}

watch(() => props.api.version.value, async () => {
  await nextTick();
  const draggerId = drag.value?.tileId ?? null;
  const gdSet = groupDragSet.value;
  for (const t of props.api.tiles.value) {
    const x = t.col * colSize.value + halfGap.value;
    const y = t.row * rowSize.value + halfGap.value;
    if (t.id === draggerId || gdSet.has(t.id)) {
      prevRects.set(t.id, { x, y });
      continue;
    }
    const p = prevRects.get(t.id);
    const node = tileNodes.get(t.id);
    if (p && node) {
      const dx = p.x - x;
      const dy = p.y - y;
      if (dx !== 0 || dy !== 0) {
        node.style.transition = 'none';
        node.style.transform = `translate(${dx}px, ${dy}px)`;
        requestAnimationFrame(() => {
          node.style.transition = 'transform 220ms cubic-bezier(.2,.7,.2,1)';
          node.style.transform = 'translate(0,0)';
        });
      }
    }
    prevRects.set(t.id, { x, y });
  }
});

// Compute layouts for all rendered tiles in one pass so resolveStickyStacking
// can see every sticky tile and adjust them as a group. Recomputes whenever
// rendered, config, viewport, drag, resize, or pinDrag change.
const tileLayouts = computed(() => {
  const out = new Map<string, TileLayout>();
  const stickyEntries: { tile: Tile; layout: TileLayout }[] = [];
  const gd = groupDrag.value;
  const gdIds = groupDragSet.value;
  for (const tile of rendered.value) {
    let layout: TileLayout;
    if (resize.value?.tileId === tile.id) {
      const w = resize.value.previewW;
      const h = resize.value.previewH;
      layout = {
        left: resize.value.previewCol * colSize.value + halfGap.value,
        top: resize.value.previewRow * rowSize.value + halfGap.value,
        width: w * config.value.unitWidth + (w - 1) * gap.value,
        height: h * config.value.unitHeight + (h - 1) * gap.value,
        zIndex: 10,
        effective: 'static',
      };
    } else if (drag.value?.tileId === tile.id) {
      const d = drag.value;
      layout = {
        left: d.pickupCol * colSize.value + halfGap.value,
        top: d.pickupRow * rowSize.value + halfGap.value,
        width: tile.w * config.value.unitWidth + (tile.w - 1) * gap.value,
        height: tile.h * config.value.unitHeight + (tile.h - 1) * gap.value,
        transform: `translate(${d.deltaX}px, ${d.deltaY}px)`,
        zIndex: 20,
        effective: 'static',
      };
    } else if (gd && gdIds.has(tile.id)) {
      const pickup = groupDragController.pickupCell(tile.id);
      const left = (pickup ? pickup.col * colSize.value : tile.col * colSize.value) + halfGap.value;
      const top = (pickup ? pickup.row * rowSize.value : tile.row * rowSize.value) + halfGap.value;
      layout = {
        left,
        top,
        width: tile.w * config.value.unitWidth + (tile.w - 1) * gap.value,
        height: tile.h * config.value.unitHeight + (tile.h - 1) * gap.value,
        transform: `translate(${gd.deltaX}px, ${gd.deltaY}px)`,
        zIndex: 20,
        effective: 'static',
      };
    } else {
      layout = computeTileLayout({
        tile,
        config: config.value,
        scrollX: viewport.value.scrollX,
        scrollY: viewport.value.scrollY,
        viewportWidth: viewport.value.width,
        viewportHeight: viewport.value.height,
      });
      if (layout.effective === 'sticky') {
        stickyEntries.push({ tile, layout });
      }
    }
    out.set(tile.id, layout);
  }
  if (stickyEntries.length > 1) resolveStickyStacking(stickyEntries);
  return out;
});

function tileStyle(tile: Tile) {
  const isDragging = drag.value?.tileId === tile.id;
  const isGroupDragging = groupDragSet.value.has(tile.id) && groupDrag.value !== null;
  const isPinDragging = pinDrag.value?.tileId === tile.id;
  const isResizing = resize.value?.tileId === tile.id;
  const isSelected = selection.value.has(tile.id);
  const layout = tileLayouts.value.get(tile.id) ?? {
    left: 0, top: 0, width: 0, height: 0, zIndex: 1, effective: 'static' as const,
  };
  const lifted = isDragging || isPinDragging || isGroupDragging;
  return {
    position: 'absolute' as const,
    left: layout.left + 'px',
    top: layout.top + 'px',
    width: layout.width + 'px',
    height: layout.height + 'px',
    boxSizing: 'border-box' as const,
    cursor: lifted ? 'grabbing' : 'grab',
    userSelect: 'none' as const,
    zIndex: layout.zIndex,
    opacity: lifted || isResizing ? 0.85 : 1,
    willChange: 'transform',
    transform: layout.transform ?? '',
    filter: lifted ? 'drop-shadow(0 8px 16px rgba(0,0,0,0.18))' : '',
    transition: lifted ? 'filter 120ms ease-out, opacity 120ms ease-out' : '',
    boxShadow: isSelected
      ? '0 0 0 3px rgba(59, 91, 219, 0.85), inset 0 0 0 1px rgba(59, 91, 219, 0.3)'
      : '',
    borderRadius: (config.value.tileRadius ?? 4) + 'px',
  };
}


const indicatorRect = computed(() => {
  const d = drag.value;
  if (!d || d.indicatorCol === null || d.indicatorRow === null) return null;
  const t = props.api.grid.getTile(d.tileId);
  if (!t) return null;
  return {
    left: d.indicatorCol * colSize.value + halfGap.value,
    top: d.indicatorRow * rowSize.value + halfGap.value,
    width: t.w * config.value.unitWidth + (t.w - 1) * gap.value,
    height: t.h * config.value.unitHeight + (t.h - 1) * gap.value,
  };
});

const drawGhostRect = computed(() => {
  const ds = drawState.value;
  if (!ds) return null;
  const col = Math.min(ds.anchorCol, ds.currentCol);
  const row = Math.min(ds.anchorRow, ds.currentRow);
  const w = Math.max(1, Math.abs(ds.currentCol - ds.anchorCol) + 1);
  const h = Math.max(1, Math.abs(ds.currentRow - ds.anchorRow) + 1);
  return {
    left: col * colSize.value + halfGap.value,
    top: row * rowSize.value + halfGap.value,
    width: w * config.value.unitWidth + (w - 1) * gap.value,
    height: h * config.value.unitHeight + (h - 1) * gap.value,
    label: `${w}×${h}`,
  };
});

function handleStyle(c: Corner) {
  const size = 12;
  const base = {
    position: 'absolute' as const,
    width: size + 'px',
    height: size + 'px',
    background: 'rgba(60,60,60,0.7)',
    border: '2px solid white',
    borderRadius: '3px',
    cursor: `${c}-resize`,
    touchAction: 'none' as const,
  } as Record<string, unknown>;
  if (c === 'nw') return { ...base, top: -size / 2 + 'px', left: -size / 2 + 'px' };
  if (c === 'ne') return { ...base, top: -size / 2 + 'px', right: -size / 2 + 'px' };
  if (c === 'sw') return { ...base, bottom: -size / 2 + 'px', left: -size / 2 + 'px' };
  return { ...base, bottom: -size / 2 + 'px', right: -size / 2 + 'px' };
}

const className = computed(() => props.className ?? '');
</script>

// packages/react/src/GriddleGrid.tsx
// GriddleGrid: the React rendering + interaction layer.
// - Virtualized tile rendering (only visible tiles are mounted)
// - Live-preview drag: as the cursor crosses cell boundaries the engine
//   continuously rewinds and re-attempts the move, so victims animate into
//   their new positions while the user is still dragging. The dragged tile
//   itself follows the cursor freely (no snap); a separate drop indicator
//   renders at the snapped candidate cell.
// - Corner resize handles
// - FLIP animations for repack — skipped for the active dragger.

import {
  CSSProperties,
  ReactNode,
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import type { GriddleApi } from './useGriddle.js';
import type { Corner, Tile } from '@griddle/core';
import {
  visibleRange,
  visibleTiles,
  gridContentSize,
  DragController,
  GroupDragController,
  computeTileLayout,
  resolveStickyStacking,
  isOutOfFlow,
  pixelsToPin,
} from '@griddle/core';
import type { TileLayout } from '@griddle/core';
import { useGridVersion } from './useGriddle.js';

export interface GriddleGridProps {
  api: GriddleApi;
  renderTile: (tile: Tile, selected: boolean) => ReactNode;
  className?: string;
  style?: CSSProperties;
  /** Optional container height; default '100%'. */
  height?: number | string;
  /** Whether to render the background grid lines. Default true. */
  showGrid?: boolean;
  /** Controlled selection state. If omitted, selection is managed internally. */
  selection?: Set<string>;
  /** Called whenever the selection changes. */
  onSelectionChange?: (selection: Set<string>) => void;
  /** Called when the user draw-creates a new tile rect on empty space. */
  onDrawCreate?: (rect: { col: number; row: number; w: number; h: number }) => void;
}

interface DragVisual {
  tileId: string;
  pickupCol: number;
  pickupRow: number;
  deltaX: number;
  deltaY: number;
  indicatorCol: number | null;
  indicatorRow: number | null;
}

interface PinDragState {
  tileId: string;
  startPinPx: { x: number; y: number };
  startPointerX: number;
  startPointerY: number;
}

interface GroupDragVisual {
  tileIds: string[];
  /** Pixel delta from pointer pickup */
  deltaX: number;
  deltaY: number;
  /** Last committed cell delta (for drop indicators) */
  committedDcol: number;
  committedDrow: number;
}

interface ResizeState {
  tileId: string;
  corner: Corner;
  startPointerX: number;
  startPointerY: number;
  startW: number;
  startH: number;
  startCol: number;
  startRow: number;
  previewW: number;
  previewH: number;
  previewCol: number;
  previewRow: number;
}

interface DrawState {
  anchorCol: number;
  anchorRow: number;
  currentCol: number;
  currentRow: number;
}

export function GriddleGrid(props: GriddleGridProps) {
  const {
    api, renderTile, className, style, height = '100%', showGrid = true,
    selection: controlledSelection, onSelectionChange, onDrawCreate,
  } = props;
  const config = api.config;
  const version = useGridVersion(api.grid);

  // Selection state (internal or controlled)
  const [internalSelection, setInternalSelection] = useState<Set<string>>(new Set());
  const selection = controlledSelection ?? internalSelection;
  const setSelection = useCallback((next: Set<string>) => {
    if (!controlledSelection) setInternalSelection(next);
    onSelectionChange?.(next);
  }, [controlledSelection, onSelectionChange]);

  // Virtualization viewport
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const [viewport, setViewport] = useState({ scrollX: 0, scrollY: 0, width: 1000, height: 800 });

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const update = () => {
      setViewport({
        scrollX: el.scrollLeft,
        scrollY: el.scrollTop,
        width: el.clientWidth,
        height: el.clientHeight,
      });
    };
    update();
    el.addEventListener('scroll', update, { passive: true });
    const ro = new ResizeObserver(update);
    ro.observe(el);
    return () => {
      el.removeEventListener('scroll', update);
      ro.disconnect();
    };
  }, []);

  const tiles = api.tiles;
  const _ = version; // subscribe

  const range = useMemo(() => visibleRange(config, viewport, 4), [config, viewport]);
  const rendered = useMemo(() => visibleTiles(tiles, range), [tiles, range]);
  const contentSize = useMemo(() => gridContentSize(config, tiles), [config, tiles]);

  const gap = config.gap ?? 0;
  const halfGap = gap / 2;
  const colSize = config.unitWidth + gap;
  const rowSize = config.unitHeight + gap;

  // Drag controller (lives across drags) + ephemeral visual state
  const dragControllerRef = useRef<DragController | null>(null);
  if (!dragControllerRef.current) {
    dragControllerRef.current = new DragController(api.grid);
  }
  const groupDragControllerRef = useRef<GroupDragController | null>(null);
  if (!groupDragControllerRef.current) {
    groupDragControllerRef.current = new GroupDragController(api.grid);
  }
  const [drag, setDrag] = useState<DragVisual | null>(null);
  const [groupDrag, setGroupDrag] = useState<GroupDragVisual | null>(null);
  const [resize, setResize] = useState<ResizeState | null>(null);
  const [pinDrag, setPinDrag] = useState<PinDragState | null>(null);
  const dragRef = useRef<DragVisual | null>(null);
  const groupDragRef = useRef<GroupDragVisual | null>(null);
  const resizeRef = useRef<ResizeState | null>(null);
  const pinDragRef = useRef<PinDragState | null>(null);
  dragRef.current = drag;
  groupDragRef.current = groupDrag;
  resizeRef.current = resize;
  pinDragRef.current = pinDrag;
  const dragStartPointerRef = useRef<{ x: number; y: number }>({ x: 0, y: 0 });

  const [drawState, setDrawState] = useState<DrawState | null>(null);
  const drawStateRef = useRef<DrawState | null>(null);
  drawStateRef.current = drawState;

  // FLIP animation state: previousRects by id. Skip the dragger during drag —
  // it has its own cursor-driven inline transform.
  const prevRectsRef = useRef(new Map<string, { x: number; y: number; w: number; h: number }>());
  const tileNodes = useRef(new Map<string, HTMLDivElement>());

  useLayoutEffect(() => {
    const prev = prevRectsRef.current;
    const next = new Map<string, { x: number; y: number; w: number; h: number }>();
    const draggerId = dragRef.current?.tileId ?? null;
    const groupDragIds = new Set(groupDragRef.current?.tileIds ?? []);
    for (const t of tiles) {
      const x = t.col * colSize + halfGap;
      const y = t.row * rowSize + halfGap;
      const w = t.w * config.unitWidth + (t.w - 1) * gap;
      const h = t.h * config.unitHeight + (t.h - 1) * gap;
      next.set(t.id, { x, y, w, h });
      if (t.id === draggerId || groupDragIds.has(t.id)) continue;
      const p = prev.get(t.id);
      const node = tileNodes.current.get(t.id);
      if (p && node) {
        const dx = p.x - x;
        const dy = p.y - y;
        if (dx !== 0 || dy !== 0) {
          node.style.transition = 'none';
          node.style.transform = `translate(${dx}px, ${dy}px)`;
          requestAnimationFrame(() => {
            node.style.transition = 'transform 220ms cubic-bezier(.2,.7,.2,1)';
            node.style.transform = 'translate(0,0)';
          });
        }
      }
    }
    prevRectsRef.current = next;
  }, [tiles, version, colSize, rowSize, config.unitWidth, config.unitHeight, config.gap]);

  // --- drag handlers ---
  const onTilePointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>, tile: Tile) => {
      if (tile.draggable === false) return;
      if ((e.target as HTMLElement).dataset.griddleHandle) return;

      const metaKey = e.metaKey || e.ctrlKey;

      // Out-of-flow tiles get free-pixel drag (no selection behavior).
      if (config.enablePositioning && isOutOfFlow(tile)) {
        (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
        const layout = computeTileLayout({
          tile,
          config,
          scrollX: viewport.scrollX,
          scrollY: viewport.scrollY,
          viewportWidth: viewport.width,
          viewportHeight: viewport.height,
        });
        const startPinPx =
          tile.position === 'fixed'
            ? { x: layout.left - viewport.scrollX, y: layout.top - viewport.scrollY }
            : { x: layout.left, y: layout.top };
        setPinDrag({
          tileId: tile.id,
          startPinPx,
          startPointerX: e.clientX,
          startPointerY: e.clientY,
        });
        e.stopPropagation();
        return;
      }

      // Cmd/Ctrl+click toggles the tile in/out of the selection without
      // starting any drag. No pointer capture needed.
      if (metaKey) {
        e.preventDefault();
        const next = new Set(selection);
        if (next.has(tile.id)) {
          next.delete(tile.id);
        } else {
          next.add(tile.id);
        }
        setSelection(next);
        e.stopPropagation();
        return;
      }

      const tileIsSelected = selection.has(tile.id);

      if (!tileIsSelected) {
        setSelection(new Set([tile.id]));
      }

      // Capture pointer only when starting a drag.
      (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);

      // Determine if this should be a group drag (2+ selected tiles including this one).
      const effectiveSelection = tileIsSelected ? selection : new Set([tile.id]);
      if (effectiveSelection.size > 1) {
        const ids = Array.from(effectiveSelection);
        const ctrl = groupDragControllerRef.current!;
        if (!ctrl.start(ids)) return;
        dragStartPointerRef.current = { x: e.clientX, y: e.clientY };
        setGroupDrag({
          tileIds: ids,
          deltaX: 0,
          deltaY: 0,
          committedDcol: 0,
          committedDrow: 0,
        });
        e.stopPropagation();
        return;
      }

      // Single tile drag.
      const ctrl = dragControllerRef.current!;
      if (!ctrl.start(tile.id)) return;
      dragStartPointerRef.current = { x: e.clientX, y: e.clientY };
      setDrag({
        tileId: tile.id,
        pickupCol: tile.col,
        pickupRow: tile.row,
        deltaX: 0,
        deltaY: 0,
        indicatorCol: tile.col,
        indicatorRow: tile.row,
      });
      e.stopPropagation();
    },
    [config, viewport, selection, setSelection],
  );

  const onPointerMove = useCallback(
    (e: PointerEvent) => {
      if (drawStateRef.current) {
        const el = scrollRef.current;
        if (el) {
          const rect = el.getBoundingClientRect();
          const x = e.clientX - rect.left + el.scrollLeft;
          const y = e.clientY - rect.top + el.scrollTop;
          const col = Math.max(0, Math.floor(x / colSize));
          const row = Math.max(0, Math.floor(y / rowSize));
          setDrawState({ ...drawStateRef.current, currentCol: col, currentRow: row });
        }
        return;
      }
      const pd = pinDragRef.current;
      const d = dragRef.current;
      const gd = groupDragRef.current;
      const r = resizeRef.current;
      if (pd) {
        const dx = e.clientX - pd.startPointerX;
        const dy = e.clientY - pd.startPointerY;
        const newPinPx = {
          x: pd.startPinPx.x + dx,
          y: pd.startPinPx.y + dy,
        };
        const newPin = pixelsToPin(newPinPx, config);
        api.grid.setTilePinned(pd.tileId, newPin);
      }
      if (gd) {
        const dx = e.clientX - dragStartPointerRef.current.x;
        const dy = e.clientY - dragStartPointerRef.current.y;
        const dcol = Math.round(dx / colSize);
        const drow = Math.round(dy / rowSize);
        const result = groupDragControllerRef.current!.update({ dcol, drow });
        setGroupDrag({
          ...gd,
          deltaX: dx,
          deltaY: dy,
          committedDcol: result.indicatorDelta?.dcol ?? gd.committedDcol,
          committedDrow: result.indicatorDelta?.drow ?? gd.committedDrow,
        });
      }
      if (d) {
        const dx = e.clientX - dragStartPointerRef.current.x;
        const dy = e.clientY - dragStartPointerRef.current.y;
        const candidateCol = d.pickupCol + Math.round(dx / colSize);
        const candidateRow = d.pickupRow + Math.round(dy / rowSize);
        const result = dragControllerRef.current!.update({
          col: candidateCol,
          row: candidateRow,
        });
        setDrag({
          ...d,
          deltaX: dx,
          deltaY: dy,
          indicatorCol: result.indicatorCell ? result.indicatorCell.col : null,
          indicatorRow: result.indicatorCell ? result.indicatorCell.row : null,
        });
      }
      if (r) {
        const dx = e.clientX - r.startPointerX;
        const dy = e.clientY - r.startPointerY;
        let dw = 0, dh = 0, dcol = 0, drow = 0;
        const stepsX = Math.round(dx / colSize);
        const stepsY = Math.round(dy / rowSize);
        if (r.corner === 'se' || r.corner === 'ne') dw = stepsX;
        if (r.corner === 'se' || r.corner === 'sw') dh = stepsY;
        if (r.corner === 'sw' || r.corner === 'nw') { dw = -stepsX; dcol = stepsX; }
        if (r.corner === 'ne' || r.corner === 'nw') { dh = -stepsY; drow = stepsY; }
        const newW = Math.max(1, r.startW + dw);
        const newH = Math.max(1, r.startH + dh);
        const newCol = r.startCol + dcol;
        const newRow = r.startRow + drow;
        if (newW !== r.previewW || newH !== r.previewH || newCol !== r.previewCol || newRow !== r.previewRow) {
          setResize({ ...r, previewW: newW, previewH: newH, previewCol: newCol, previewRow: newRow });
        }
      }
    },
    [colSize, rowSize, api, config],
  );

  const onDrawCreateRef = useRef(onDrawCreate);
  onDrawCreateRef.current = onDrawCreate;

  const onPointerUp = useCallback(() => {
    if (drawStateRef.current) {
      const ds = drawStateRef.current;
      const col = Math.min(ds.anchorCol, ds.currentCol);
      const row = Math.min(ds.anchorRow, ds.currentRow);
      const w = Math.max(1, Math.abs(ds.currentCol - ds.anchorCol) + 1);
      const h = Math.max(1, Math.abs(ds.currentRow - ds.anchorRow) + 1);
      setDrawState(null);
      onDrawCreateRef.current?.({ col, row, w, h });
      return;
    }
    const pd = pinDragRef.current;
    const d = dragRef.current;
    const gd = groupDragRef.current;
    const r = resizeRef.current;
    if (pd) {
      setPinDrag(null);
    }
    if (gd) {
      groupDragControllerRef.current!.end();
      setGroupDrag(null);
    }
    if (d) {
      dragControllerRef.current!.end();
      setDrag(null);
    }
    if (r) {
      const tile = api.grid.getTile(r.tileId);
      if (tile) {
        if (r.previewCol !== tile.col || r.previewRow !== tile.row) {
          api.moveTile(r.tileId, { col: r.previewCol, row: r.previewRow });
        }
        if (r.previewW !== tile.w || r.previewH !== tile.h) {
          api.resizeTile(r.tileId, { w: r.previewW, h: r.previewH });
        }
      }
      setResize(null);
    }
  }, [api]);

  useEffect(() => {
    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', onPointerUp);
    window.addEventListener('pointercancel', onPointerUp);
    return () => {
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerup', onPointerUp);
      window.removeEventListener('pointercancel', onPointerUp);
    };
  }, [onPointerMove, onPointerUp]);

  // Escape key clears selection.
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setSelection(new Set());
      }
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [setSelection]);

  // Click on empty space clears selection and starts draw-to-create.
  const onBackgroundPointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if ((e.target as HTMLElement).closest('[data-griddle-tile]')) return;
      setSelection(new Set());

      const el = scrollRef.current;
      if (!el) return;
      const rect = el.getBoundingClientRect();
      const x = e.clientX - rect.left + el.scrollLeft;
      const y = e.clientY - rect.top + el.scrollTop;
      const col = Math.floor(x / colSize);
      const row = Math.floor(y / rowSize);
      setDrawState({ anchorCol: col, anchorRow: row, currentCol: col, currentRow: row });
      el.setPointerCapture(e.pointerId);
    },
    [setSelection, colSize, rowSize],
  );

  const onResizeHandleDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>, tile: Tile, corner: Corner) => {
      if (tile.resizable === false) return;
      (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
      setResize({
        tileId: tile.id,
        corner,
        startPointerX: e.clientX,
        startPointerY: e.clientY,
        startW: tile.w,
        startH: tile.h,
        startCol: tile.col,
        startRow: tile.row,
        previewW: tile.w,
        previewH: tile.h,
        previewCol: tile.col,
        previewRow: tile.row,
      });
      e.stopPropagation();
    },
    [],
  );

  // Background grid lines via CSS
  const bgStyle: CSSProperties = showGrid
    ? {
        backgroundImage: `linear-gradient(to right, rgba(0,0,0,0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,0,0,0.08) 1px, transparent 1px)`,
        backgroundSize: `${colSize}px ${rowSize}px`,
        backgroundPosition: '0 0',
      }
    : {};

  const handles = config.resizeHandles ?? ['se'];

  // Compute layouts for all rendered tiles in one pass so resolveStickyStacking
  // can see every sticky tile and adjust them as a group. Recomputes whenever
  // the relevant inputs change.
  const groupDragSet = useMemo(
    () => new Set(groupDrag?.tileIds ?? []),
    [groupDrag?.tileIds],
  );
  const tileLayouts = useMemo(() => {
    const out = new Map<string, TileLayout>();
    const stickyEntries: { tile: Tile; layout: TileLayout }[] = [];
    for (const tile of rendered) {
      let layout: TileLayout;
      if (resize?.tileId === tile.id) {
        const w = resize.previewW;
        const h = resize.previewH;
        layout = {
          left: resize.previewCol * colSize + halfGap,
          top: resize.previewRow * rowSize + halfGap,
          width: w * config.unitWidth + (w - 1) * gap,
          height: h * config.unitHeight + (h - 1) * gap,
          zIndex: 10,
          effective: 'static',
        };
      } else if (drag?.tileId === tile.id) {
        layout = {
          left: drag.pickupCol * colSize + halfGap,
          top: drag.pickupRow * rowSize + halfGap,
          width: tile.w * config.unitWidth + (tile.w - 1) * gap,
          height: tile.h * config.unitHeight + (tile.h - 1) * gap,
          transform: `translate(${drag.deltaX}px, ${drag.deltaY}px)`,
          zIndex: 20,
          effective: 'static',
        };
      } else if (groupDrag && groupDragSet.has(tile.id)) {
        const pickup = groupDragControllerRef.current!.pickupCell(tile.id);
        const left = (pickup ? pickup.col * colSize : tile.col * colSize) + halfGap;
        const top = (pickup ? pickup.row * rowSize : tile.row * rowSize) + halfGap;
        layout = {
          left,
          top,
          width: tile.w * config.unitWidth + (tile.w - 1) * gap,
          height: tile.h * config.unitHeight + (tile.h - 1) * gap,
          transform: `translate(${groupDrag.deltaX}px, ${groupDrag.deltaY}px)`,
          zIndex: 20,
          effective: 'static',
        };
      } else {
        layout = computeTileLayout({
          tile,
          config,
          scrollX: viewport.scrollX,
          scrollY: viewport.scrollY,
          viewportWidth: viewport.width,
          viewportHeight: viewport.height,
        });
        if (layout.effective === 'sticky') {
          stickyEntries.push({ tile, layout });
        }
      }
      out.set(tile.id, layout);
    }
    if (stickyEntries.length > 1) resolveStickyStacking(stickyEntries);
    return out;
  }, [rendered, drag, groupDrag, groupDragSet, resize, config, viewport, colSize, rowSize]);

  // Drop indicator rect (snapped to candidate cell, sized to dragger).
  let indicatorRect: { left: number; top: number; width: number; height: number } | null = null;
  if (drag && drag.indicatorCol !== null && drag.indicatorRow !== null) {
    const t = api.grid.getTile(drag.tileId);
    if (t) {
      indicatorRect = {
        left: drag.indicatorCol * colSize + halfGap,
        top: drag.indicatorRow * rowSize + halfGap,
        width: t.w * config.unitWidth + (t.w - 1) * gap,
        height: t.h * config.unitHeight + (t.h - 1) * gap,
      };
    }
  }

  // Draw-to-create ghost rect.
  let drawGhost: { left: number; top: number; width: number; height: number; label: string } | null = null;
  if (drawState) {
    const col = Math.min(drawState.anchorCol, drawState.currentCol);
    const row = Math.min(drawState.anchorRow, drawState.currentRow);
    const w = Math.max(1, Math.abs(drawState.currentCol - drawState.anchorCol) + 1);
    const h = Math.max(1, Math.abs(drawState.currentRow - drawState.anchorRow) + 1);
    drawGhost = {
      left: col * colSize + halfGap,
      top: row * rowSize + halfGap,
      width: w * config.unitWidth + (w - 1) * gap,
      height: h * config.unitHeight + (h - 1) * gap,
      label: `${w}\u00d7${h}`,
    };
  }

  return (
    <div
      ref={scrollRef}
      className={className}
      onPointerDown={onBackgroundPointerDown}
      style={{
        position: 'relative',
        overflow: 'auto',
        height,
        touchAction: 'none',
        ...style,
      }}
    >
      <div
        style={{
          position: 'relative',
          width: contentSize.width || '100%',
          height: contentSize.height || '100%',
          minWidth: '100%',
          minHeight: '100%',
          // Expose the tile radius as a CSS var so user tile components can
          // read it with var(--griddle-tile-radius) and stay in sync.
          ['--griddle-tile-radius' as never]: `${config.tileRadius ?? 4}px`,
          ...bgStyle,
        }}
      >
        {indicatorRect && (
          <div
            style={{
              position: 'absolute',
              left: indicatorRect.left,
              top: indicatorRect.top,
              width: indicatorRect.width,
              height: indicatorRect.height,
              boxSizing: 'border-box',
              border: '2px dashed rgba(59, 91, 219, 0.55)',
              background: 'rgba(59, 91, 219, 0.08)',
              borderRadius: config.tileRadius ?? 4,
              pointerEvents: 'none',
              zIndex: 5,
            }}
          />
        )}
        {drawGhost && (
          <div
            style={{
              position: 'absolute',
              left: drawGhost.left,
              top: drawGhost.top,
              width: drawGhost.width,
              height: drawGhost.height,
              boxSizing: 'border-box',
              border: '2px dashed rgba(59, 91, 219, 0.55)',
              background: 'rgba(59, 91, 219, 0.08)',
              borderRadius: config.tileRadius ?? 4,
              pointerEvents: 'none',
              zIndex: 5,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: 14,
              fontWeight: 600,
              color: 'rgba(59, 91, 219, 0.8)',
              userSelect: 'none',
            }}
          >
            {drawGhost.label}
          </div>
        )}
        {rendered.map((tile) => {
          const isDragging = drag?.tileId === tile.id;
          const isGroupDragging = groupDragSet.has(tile.id);
          const isPinDragging = pinDrag?.tileId === tile.id;
          const isResizing = resize?.tileId === tile.id;
          const isSelected = selection.has(tile.id);
          const tileHandles = tile.resizeHandles ?? handles;

          const layout = tileLayouts.get(tile.id) ?? {
            left: 0, top: 0, width: 0, height: 0, zIndex: 1, effective: 'static' as const,
          };
          const left = layout.left;
          const top = layout.top;
          const width = layout.width;
          const heightPx = layout.height;
          const transform = layout.transform;
          const zIndex = layout.zIndex;

          const lifted = isDragging || isPinDragging || (isGroupDragging && groupDrag !== null);
          const tileStyle: CSSProperties = {
            position: 'absolute',
            left,
            top,
            width,
            height: heightPx,
            boxSizing: 'border-box',
            cursor: lifted ? 'grabbing' : 'grab',
            userSelect: 'none',
            zIndex,
            opacity: lifted || isResizing ? 0.85 : 1,
            willChange: 'transform',
            transform,
            filter: lifted ? 'drop-shadow(0 8px 16px rgba(0,0,0,0.18))' : undefined,
            transition: lifted ? 'filter 120ms ease-out, opacity 120ms ease-out' : undefined,
            boxShadow: isSelected
              ? '0 0 0 3px rgba(59, 91, 219, 0.85), inset 0 0 0 1px rgba(59, 91, 219, 0.3)'
              : undefined,
            borderRadius: config.tileRadius ?? 4,
          };

          return (
            <div
              key={tile.id}
              ref={(el) => {
                if (el) tileNodes.current.set(tile.id, el);
                else tileNodes.current.delete(tile.id);
              }}
              data-griddle-tile={tile.id}
              onPointerDown={(e) => onTilePointerDown(e, tile)}
              style={tileStyle}
            >
              {renderTile(tile, isSelected)}
              {tile.resizable !== false &&
                tileHandles.map((c) => (
                  <div
                    key={c}
                    data-griddle-handle={c}
                    onPointerDown={(e) => onResizeHandleDown(e, tile, c)}
                    style={handleStyle(c)}
                  />
                ))}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function handleStyle(c: Corner): CSSProperties {
  const size = 12;
  const base: CSSProperties = {
    position: 'absolute',
    width: size,
    height: size,
    background: 'rgba(60,60,60,0.7)',
    border: '2px solid white',
    borderRadius: 3,
    cursor: `${c}-resize`,
    touchAction: 'none',
  };
  if (c === 'nw') return { ...base, top: -size / 2, left: -size / 2 };
  if (c === 'ne') return { ...base, top: -size / 2, right: -size / 2 };
  if (c === 'sw') return { ...base, bottom: -size / 2, left: -size / 2 };
  return { ...base, bottom: -size / 2, right: -size / 2 };
}
