// packages/react/src/LoopGrid.tsx
// GriddleLoopGrid: loop-mode renderer ("object looping").
//
// The packed content (bounding box of the in-flow tiles) repeats infinitely
// in both axes. There is NO native scrolling: the viewport is an
// overflow-hidden box and an unbounded PanController camera translates a
// zero-sized "plane" element via CSS transform. Wheel deltas and (optionally)
// drag-to-pan feed the camera. Because nothing has scrollable overflow, no
// scrollbars appear and the component can never affect page layout.
//
// Interactions:
// - 'pan'  — drag anywhere pans the camera with configurable physics. Tiles
//            are view-only (no drag / resize / selection / draw-create).
// - 'edit' — "ghost edit": only the base copy (kx=0, ky=0) is interactive,
//            with ordinary non-wrapped grid semantics (drag, resize,
//            selection). The surrounding repeats render live but are
//            pointer-transparent ghosts (data-griddle-ghost, dimmed), so
//            seams preview in real time while editing stays plain-grid.
//            Wheel pans, and dragging anywhere outside the base copy pans.

import {
  CSSProperties,
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import type { Corner, Tile, CameraState, LoopTileInstance } from '@griddle/core';
import {
  DragController,
  PanController,
  loopInstances,
  loopPeriod,
  resolveLoop,
} from '@griddle/core';
import type { GriddleGridProps } from './GriddleGrid.js';
import { useGridVersion } from './useGriddle.js';

const DEFAULT_DRAG_IGNORE = 'a, button, input, textarea, select, [contenteditable]';
const PAN_THRESHOLD_PX = 4;

interface LoopView {
  /** Quantized camera position, in whole cells (world space). */
  cxCell: number;
  cyCell: number;
  /** Viewport pixel size. */
  vw: number;
  vh: number;
}

interface LoopDragVisual {
  tileId: string;
  /** World-space origin of the grabbed instance at pickup. */
  instanceLeft: number;
  instanceTop: number;
  pickupCol: number;
  pickupRow: number;
  deltaX: number;
  deltaY: number;
  indicatorCol: number | null;
  indicatorRow: number | null;
}

interface LoopResizeState {
  tileId: string;
  /** Key of the grabbed instance — only this copy previews live. */
  instanceKey: string;
  /** World-space period offset of the grabbed instance. */
  instanceDx: number;
  instanceDy: number;
  corner: Corner;
  startPointerX: number;
  startPointerY: number;
  startW: number;
  startH: number;
  startCol: number;
  startRow: number;
  previewW: number;
  previewH: number;
  previewCol: number;
  previewRow: number;
}

export function GriddleLoopGrid(props: GriddleGridProps) {
  const {
    api, renderTile, className, style, height = '100%', showGrid = true,
    selection: controlledSelection, onSelectionChange,
    onDragStart, onDragEnd, onResizeStart, onResizeEnd, onCameraChange,
  } = props;
  const config = api.config;
  const version = useGridVersion(api.grid);
  const loop = useMemo(() => resolveLoop(config), [config]);
  const interaction = loop?.interaction ?? 'pan';
  const editable = interaction === 'edit';

  const gap = config.gap ?? 0;
  const halfGap = gap / 2;
  const colSize = config.unitWidth + gap;
  const rowSize = config.unitHeight + gap;

  const tiles = api.tiles;
  const _ = version; // subscribe
  const period = useMemo(() => loopPeriod(config, tiles), [config, tiles]);
  const periodRef = useRef(period);
  periodRef.current = period;

  // Selection (edit mode only).
  const [internalSelection, setInternalSelection] = useState<Set<string>>(new Set());
  const selection = controlledSelection ?? internalSelection;
  const setSelection = useCallback((next: Set<string>) => {
    if (!controlledSelection) setInternalSelection(next);
    onSelectionChange?.(next);
  }, [controlledSelection, onSelectionChange]);

  // Camera plumbing: the PanController is the single source of truth; the
  // rAF loop applies it to the plane transform imperatively (no re-render)
  // and publishes a cell-quantized view for virtualization.
  const viewportRef = useRef<HTMLDivElement | null>(null);
  const planeRef = useRef<HTMLDivElement | null>(null);
  const panRef = useRef<PanController | null>(null);
  if (!panRef.current) panRef.current = new PanController();
  const [view, setView] = useState<LoopView>({ cxCell: 0, cyCell: 0, vw: 1000, vh: 800 });
  const viewRef = useRef(view);
  viewRef.current = view;

  const onCameraChangeRef = useRef(onCameraChange);
  onCameraChangeRef.current = onCameraChange;
  const lastCamRef = useRef<CameraState | null>(null);

  useEffect(() => {
    if (loop) {
      panRef.current!.setPhysics({
        friction: loop.friction,
        ease: loop.ease,
        maxVelocity: loop.maxVelocity,
      });
    }
  }, [loop]);

  // Wheel pans the camera ("native scroll" feel without scroll).
  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const k = e.deltaMode === 1 ? 16 : e.deltaMode === 2 ? 100 : 1;
      panRef.current!.scrollBy(e.deltaX * k, e.deltaY * k);
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, []);

  // Track viewport size.
  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;
    const measure = () => {
      const vw = el.clientWidth;
      const vh = el.clientHeight;
      const cur = viewRef.current;
      if (vw !== cur.vw || vh !== cur.vh) setView({ ...cur, vw, vh });
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // rAF loop: advance physics, move the plane, publish the quantized view.
  useEffect(() => {
    let raf = 0;
    const frame = (now: number) => {
      raf = requestAnimationFrame(frame);
      const pan = panRef.current!;
      const st = pan.tick(now);

      const plane = planeRef.current;
      if (plane) {
        plane.style.transform = `translate3d(${-st.x}px, ${-st.y}px, 0)`;
      }
      const el = viewportRef.current;
      if (el && showGrid) {
        el.style.backgroundPosition = `${-st.x % colSize}px ${-st.y % rowSize}px`;
      }

      const cxCell = Math.floor(st.x / colSize);
      const cyCell = Math.floor(st.y / rowSize);
      const cur = viewRef.current;
      if (cxCell !== cur.cxCell || cyCell !== cur.cyCell) {
        setView({ ...cur, cxCell, cyCell });
      }

      const last = lastCamRef.current;
      if (
        !last || last.x !== st.x || last.y !== st.y ||
        last.isMoving !== st.isMoving || last.isDragging !== st.isDragging
      ) {
        lastCamRef.current = st;
        onCameraChangeRef.current?.(st);
      }
    };
    raf = requestAnimationFrame(frame);
    return () => cancelAnimationFrame(raf);
  }, [colSize, rowSize, showGrid]);

  // Visible instances: camera window padded by a 2-cell buffer.
  const instances = useMemo(() => {
    const bufX = 2 * colSize;
    const bufY = 2 * rowSize;
    return loopInstances(config, tiles, {
      x: view.cxCell * colSize - bufX,
      y: view.cyCell * rowSize - bufY,
      width: view.vw + colSize + 2 * bufX,
      height: view.vh + rowSize + 2 * bufY,
    });
  }, [config, tiles, view, colSize, rowSize, version]);

  // ---- pan gesture --------------------------------------------------------
  const panGestureRef = useRef<{
    pointerId: number;
    startX: number;
    startY: number;
    moved: boolean;
  } | null>(null);
  const suppressClickRef = useRef(false);

  const onContainerPointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if (!loop?.dragPan) return;
      if (e.button !== 0) return;
      const ignoreSelector = config.dragIgnoreFrom ?? DEFAULT_DRAG_IGNORE;
      if (ignoreSelector && (e.target as HTMLElement).closest(ignoreSelector)) return;
      panGestureRef.current = {
        pointerId: e.pointerId,
        startX: e.clientX,
        startY: e.clientY,
        moved: false,
      };
    },
    [loop?.dragPan, config.dragIgnoreFrom],
  );

  const onContainerClickCapture = useCallback((e: React.MouseEvent) => {
    if (suppressClickRef.current) {
      suppressClickRef.current = false;
      e.preventDefault();
      e.stopPropagation();
    }
  }, []);

  // ---- tile drag / resize ('edit' interaction) ----------------------------
  const dragControllerRef = useRef<DragController | null>(null);
  if (!dragControllerRef.current) dragControllerRef.current = new DragController(api.grid);
  const [drag, setDrag] = useState<LoopDragVisual | null>(null);
  const [resize, setResize] = useState<LoopResizeState | null>(null);
  const dragRef = useRef<LoopDragVisual | null>(null);
  const resizeRef = useRef<LoopResizeState | null>(null);
  dragRef.current = drag;
  resizeRef.current = resize;
  const dragStartPointerRef = useRef({ x: 0, y: 0 });

  const onDragStartRef = useRef(onDragStart);
  onDragStartRef.current = onDragStart;
  const onDragEndRef = useRef(onDragEnd);
  onDragEndRef.current = onDragEnd;
  const onResizeStartRef = useRef(onResizeStart);
  onResizeStartRef.current = onResizeStart;
  const onResizeEndRef = useRef(onResizeEnd);
  onResizeEndRef.current = onResizeEnd;

  const onTilePointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>, inst: LoopTileInstance) => {
      if (!editable) return; // pan mode: bubble up to the container pan handler
      if (inst.kx !== 0 || inst.ky !== 0) return; // ghosts are display-only
      const tile = inst.tile;
      if (tile.draggable === false) return;
      if ((e.target as HTMLElement).dataset.griddleHandle) return;
      const ignoreSelector = config.dragIgnoreFrom ?? DEFAULT_DRAG_IGNORE;
      if (ignoreSelector && (e.target as HTMLElement).closest(ignoreSelector)) return;

      if (e.metaKey || e.ctrlKey) {
        e.preventDefault();
        const next = new Set(selection);
        if (next.has(tile.id)) next.delete(tile.id);
        else next.add(tile.id);
        setSelection(next);
        e.stopPropagation();
        return;
      }
      setSelection(new Set([tile.id]));

      // No pointer capture here: the grabbed instance unmounts (the drag
      // renders as an overlay), which would release the capture mid-gesture.
      // Window-level listeners track the pointer instead.
      const ctrl = dragControllerRef.current!;
      if (!ctrl.start(tile.id)) return;
      dragStartPointerRef.current = { x: e.clientX, y: e.clientY };
      setDrag({
        tileId: tile.id,
        instanceLeft: inst.left,
        instanceTop: inst.top,
        pickupCol: tile.col,
        pickupRow: tile.row,
        deltaX: 0,
        deltaY: 0,
        indicatorCol: tile.col,
        indicatorRow: tile.row,
      });
      onDragStartRef.current?.(tile.id);
      e.stopPropagation();
    },
    [editable, config, selection, setSelection],
  );

  const onResizeHandleDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>, inst: LoopTileInstance, corner: Corner) => {
      if (!editable) return;
      const tile = inst.tile;
      if (tile.resizable === false) return;
      (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
      const baseLeft = tile.col * colSize + halfGap;
      const baseTop = tile.row * rowSize + halfGap;
      setResize({
        tileId: tile.id,
        instanceKey: inst.key,
        instanceDx: inst.left - baseLeft,
        instanceDy: inst.top - baseTop,
        corner,
        startPointerX: e.clientX,
        startPointerY: e.clientY,
        startW: tile.w,
        startH: tile.h,
        startCol: tile.col,
        startRow: tile.row,
        previewW: tile.w,
        previewH: tile.h,
        previewCol: tile.col,
        previewRow: tile.row,
      });
      onResizeStartRef.current?.(tile.id);
      e.stopPropagation();
    },
    [editable, colSize, rowSize, halfGap],
  );

  const onPointerMove = useCallback(
    (e: PointerEvent) => {
      const pg = panGestureRef.current;
      if (pg && e.pointerId === pg.pointerId) {
        const now = performance.now();
        const pan = panRef.current!;
        if (!pg.moved) {
          const dist = Math.hypot(e.clientX - pg.startX, e.clientY - pg.startY);
          if (dist >= PAN_THRESHOLD_PX) {
            pg.moved = true;
            pan.dragStart(pg.startX, pg.startY, now);
            pan.dragMove(e.clientX, e.clientY, now);
          }
        } else {
          pan.dragMove(e.clientX, e.clientY, now);
        }
        return;
      }

      const d = dragRef.current;
      if (d) {
        // Ghost edit: plain grid semantics in the base copy — no wrapping.
        const dx = e.clientX - dragStartPointerRef.current.x;
        const dy = e.clientY - dragStartPointerRef.current.y;
        const candidate = {
          col: d.pickupCol + Math.round(dx / colSize),
          row: d.pickupRow + Math.round(dy / rowSize),
        };
        const result = dragControllerRef.current!.update(candidate);
        setDrag({
          ...d,
          deltaX: dx,
          deltaY: dy,
          indicatorCol: result.indicatorCell ? result.indicatorCell.col : null,
          indicatorRow: result.indicatorCell ? result.indicatorCell.row : null,
        });
      }

      const r = resizeRef.current;
      if (r) {
        const dx = e.clientX - r.startPointerX;
        const dy = e.clientY - r.startPointerY;
        let dw = 0, dh = 0, dcol = 0, drow = 0;
        const stepsX = Math.round(dx / colSize);
        const stepsY = Math.round(dy / rowSize);
        if (r.corner === 'se' || r.corner === 'ne') dw = stepsX;
        if (r.corner === 'se' || r.corner === 'sw') dh = stepsY;
        if (r.corner === 'sw' || r.corner === 'nw') { dw = -stepsX; dcol = stepsX; }
        if (r.corner === 'ne' || r.corner === 'nw') { dh = -stepsY; drow = stepsY; }
        const tile = api.grid.getTile(r.tileId);
        const minW = tile?.minW ?? 1;
        const minH = tile?.minH ?? 1;
        const maxW = Math.min(tile?.maxW ?? Infinity, config.cols);
        const maxH = Math.min(tile?.maxH ?? Infinity, config.rows);
        const newW = Math.min(maxW, Math.max(minW, r.startW + dw));
        const newH = Math.min(maxH, Math.max(minH, r.startH + dh));
        const newCol = r.startCol + dcol;
        const newRow = r.startRow + drow;
        if (newW !== r.previewW || newH !== r.previewH || newCol !== r.previewCol || newRow !== r.previewRow) {
          setResize({ ...r, previewW: newW, previewH: newH, previewCol: newCol, previewRow: newRow });
        }
      }
    },
    [colSize, rowSize, config, api],
  );

  const onPointerUp = useCallback(
    (e: PointerEvent) => {
      const pg = panGestureRef.current;
      if (pg && e.pointerId === pg.pointerId) {
        if (pg.moved) {
          panRef.current!.dragEnd(performance.now());
          suppressClickRef.current = true;
        }
        panGestureRef.current = null;
        return;
      }

      const d = dragRef.current;
      if (d) {
        const tileId = d.tileId;
        const { committed } = dragControllerRef.current!.end();
        setDrag(null);
        onDragEndRef.current?.(tileId, committed);
      }
      const r = resizeRef.current;
      if (r) {
        const tile = api.grid.getTile(r.tileId);
        let committed = false;
        if (tile) {
          const target = { col: r.previewCol, row: r.previewRow };
          if (target.col !== tile.col || target.row !== tile.row) {
            api.moveTile(r.tileId, target);
          }
          if (r.previewW !== tile.w || r.previewH !== tile.h) {
            committed = api.resizeTile(r.tileId, { w: r.previewW, h: r.previewH });
          } else {
            committed = r.previewCol !== r.startCol || r.previewRow !== r.startRow
              || r.previewW !== r.startW || r.previewH !== r.startH;
          }
        }
        setResize(null);
        onResizeEndRef.current?.(r.tileId, committed);
      }
    },
    [api, config],
  );

  useEffect(() => {
    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', onPointerUp);
    window.addEventListener('pointercancel', onPointerUp);
    return () => {
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerup', onPointerUp);
      window.removeEventListener('pointercancel', onPointerUp);
    };
  }, [onPointerMove, onPointerUp]);

  useEffect(() => {
    if (!editable) return;
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setSelection(new Set());
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [editable, setSelection]);

  const onBackgroundPointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if ((e.target as HTMLElement).closest('[data-griddle-tile]')) return;
      if (editable) setSelection(new Set());
    },
    [editable, setSelection],
  );

  // FLIP for edit-mode repacks, keyed by world key. Skips the active dragger
  // (overlay) and any apparent jump of >= half a period (period-size changes
  // can re-home instances).
  const prevRectsRef = useRef(new Map<string, { x: number; y: number }>());
  const tileNodes = useRef(new Map<string, HTMLDivElement>());

  useLayoutEffect(() => {
    const prev = prevRectsRef.current;
    const next = new Map<string, { x: number; y: number }>();
    const draggerId = dragRef.current?.tileId ?? null;
    for (const inst of instances) {
      const key = inst.key;
      next.set(key, { x: inst.left, y: inst.top });
      if (!editable || inst.tile.id === draggerId) continue;
      const p = prev.get(key);
      const node = tileNodes.current.get(key);
      if (p && node) {
        const dx = p.x - inst.left;
        const dy = p.y - inst.top;
        if (
          (dx !== 0 || dy !== 0) &&
          Math.abs(dx) < periodRef.current.width / 2 &&
          Math.abs(dy) < periodRef.current.height / 2
        ) {
          node.style.transition = 'none';
          node.style.transform = `translate(${dx}px, ${dy}px)`;
          requestAnimationFrame(() => {
            node.style.transition = 'transform 220ms cubic-bezier(.2,.7,.2,1)';
            node.style.transform = 'translate(0,0)';
          });
        }
      }
    }
    prevRectsRef.current = next;
  }, [instances, editable]);

  // Drop indicator: rendered in the base copy (ghost edit is plain-grid).
  let indicatorRect: { left: number; top: number; width: number; height: number } | null = null;
  if (drag && drag.indicatorCol !== null && drag.indicatorRow !== null) {
    const t = api.grid.getTile(drag.tileId);
    if (t) {
      indicatorRect = {
        left: drag.indicatorCol * colSize + halfGap,
        top: drag.indicatorRow * rowSize + halfGap,
        width: t.w * config.unitWidth + (t.w - 1) * gap,
        height: t.h * config.unitHeight + (t.h - 1) * gap,
      };
    }
  }

  // Dragged tile renders as a single overlay copy following the cursor; its
  // grid instances are hidden while the gesture is live (avoids key churn as
  // the live preview wraps its cell across the seam).
  const draggedTile = drag ? api.grid.getTile(drag.tileId) : null;

  const bgStyle: CSSProperties = showGrid
    ? {
        backgroundImage: `linear-gradient(to right, rgba(0,0,0,0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,0,0,0.08) 1px, transparent 1px)`,
        backgroundSize: `${colSize}px ${rowSize}px`,
        backgroundPosition: '0 0',
      }
    : {};

  const handles = config.resizeHandles ?? ['se'];

  return (
    <div
      ref={viewportRef}
      className={className}
      onPointerDown={(e) => {
        onContainerPointerDown(e);
        onBackgroundPointerDown(e);
      }}
      onClickCapture={onContainerClickCapture}
      style={{
        position: 'relative',
        overflow: 'hidden',
        height,
        touchAction: 'none',
        userSelect: 'none',
        cursor: !editable && loop?.dragPan ? 'grab' : undefined,
        ['--griddle-tile-radius' as never]: `${config.tileRadius ?? 4}px`,
        ...bgStyle,
        ...style,
      }}
    >
      <div
        ref={planeRef}
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: 0,
          height: 0,
          willChange: 'transform',
        }}
      >
        {indicatorRect && (
          <div
            style={{
              position: 'absolute',
              left: indicatorRect.left,
              top: indicatorRect.top,
              width: indicatorRect.width,
              height: indicatorRect.height,
              boxSizing: 'border-box',
              border: '2px dashed rgba(59, 91, 219, 0.55)',
              background: 'rgba(59, 91, 219, 0.08)',
              borderRadius: config.tileRadius ?? 4,
              pointerEvents: 'none',
              zIndex: 5,
            }}
          />
        )}
        {instances.map((inst) => {
          const tile = inst.tile;
          if (drag && tile.id === drag.tileId) return null;
          const key = inst.key;
          const isBase = inst.kx === 0 && inst.ky === 0;
          const isGhost = editable && !isBase;
          const isResizingInst = resize?.instanceKey === inst.key;
          const isSelected = editable && isBase && selection.has(tile.id);
          const tileHandles = tile.resizeHandles ?? handles;

          let left = inst.left;
          let top = inst.top;
          let width = inst.width;
          let heightPx = inst.height;
          if (isResizingInst && resize) {
            left = resize.previewCol * colSize + halfGap + resize.instanceDx;
            top = resize.previewRow * rowSize + halfGap + resize.instanceDy;
            width = resize.previewW * config.unitWidth + (resize.previewW - 1) * gap;
            heightPx = resize.previewH * config.unitHeight + (resize.previewH - 1) * gap;
          }

          const tileStyle: CSSProperties = {
            position: 'absolute',
            left,
            top,
            width,
            height: heightPx,
            boxSizing: 'border-box',
            cursor: editable && isBase ? 'grab' : undefined,
            userSelect: 'none',
            // Ghosts are display-only: pointer-transparent (so the gesture
            // falls through to drag-pan) and dimmed to mark the editable copy.
            pointerEvents: isGhost ? 'none' : undefined,
            zIndex: isResizingInst ? 10 : 1,
            opacity: isResizingInst ? 0.85 : isGhost ? 0.55 : 1,
            boxShadow: isSelected
              ? '0 0 0 3px rgba(59, 91, 219, 0.85), inset 0 0 0 1px rgba(59, 91, 219, 0.3)'
              : undefined,
            borderRadius: config.tileRadius ?? 4,
          };

          return (
            <div
              key={key}
              ref={(el) => {
                if (el) tileNodes.current.set(key, el);
                else tileNodes.current.delete(key);
              }}
              data-griddle-tile={tile.id}
              data-griddle-instance={key}
              data-griddle-ghost={isGhost ? '' : undefined}
              aria-hidden={isBase ? undefined : true}
              onPointerDown={(e) => onTilePointerDown(e, inst)}
              style={tileStyle}
            >
              {renderTile(tile, isSelected)}
              {editable && isBase && tile.resizable !== false &&
                tileHandles.map((c) => (
                  <div
                    key={c}
                    data-griddle-handle={c}
                    onPointerDown={(e) => onResizeHandleDown(e, inst, c)}
                    style={handleStyle(c)}
                  />
                ))}
            </div>
          );
        })}
        {drag && draggedTile && (
          <div
            data-griddle-tile={draggedTile.id}
            style={{
              position: 'absolute',
              left: drag.instanceLeft,
              top: drag.instanceTop,
              width: draggedTile.w * config.unitWidth + (draggedTile.w - 1) * gap,
              height: draggedTile.h * config.unitHeight + (draggedTile.h - 1) * gap,
              boxSizing: 'border-box',
              cursor: 'grabbing',
              userSelect: 'none',
              zIndex: 20,
              opacity: 0.85,
              transform: `translate(${drag.deltaX}px, ${drag.deltaY}px)`,
              filter: 'drop-shadow(0 8px 16px rgba(0,0,0,0.18))',
              borderRadius: config.tileRadius ?? 4,
              pointerEvents: 'none',
            }}
          >
            {renderTile(draggedTile, selection.has(draggedTile.id))}
          </div>
        )}
      </div>
    </div>
  );
}

function handleStyle(c: Corner): CSSProperties {
  const size = 12;
  const base: CSSProperties = {
    position: 'absolute',
    width: size,
    height: size,
    background: 'rgba(60,60,60,0.7)',
    border: '2px solid white',
    borderRadius: 3,
    cursor: `${c}-resize`,
    touchAction: 'none',
  };
  if (c === 'nw') return { ...base, top: -size / 2, left: -size / 2 };
  if (c === 'ne') return { ...base, top: -size / 2, right: -size / 2 };
  if (c === 'sw') return { ...base, bottom: -size / 2, left: -size / 2 };
  return { ...base, bottom: -size / 2, right: -size / 2 };
}

// packages/vue/src/LoopGrid.vue
<template>
  <div
    ref="viewportEl"
    :class="className"
    :style="viewportStyle"
    @pointerdown="onContainerPointerDown"
    @click.capture="onClickCapture"
  >
    <div ref="planeEl" :style="planeStyle">
      <div
        v-if="indicatorRect"
        class="griddle-drop-indicator"
        :style="{
          position: 'absolute',
          left: indicatorRect.left + 'px',
          top: indicatorRect.top + 'px',
          width: indicatorRect.width + 'px',
          height: indicatorRect.height + 'px',
          boxSizing: 'border-box',
          border: '2px dashed rgba(59, 91, 219, 0.55)',
          background: 'rgba(59, 91, 219, 0.08)',
          borderRadius: (config.tileRadius ?? 4) + 'px',
          pointerEvents: 'none',
          zIndex: 5,
        }"
      ></div>
      <template v-for="inst in instances" :key="inst.key">
        <div
          v-if="!(drag && inst.tile.id === drag.tileId)"
          :data-griddle-tile="inst.tile.id"
          :data-griddle-instance="inst.key"
          :data-griddle-ghost="isGhost(inst) ? '' : undefined"
          :aria-hidden="isBase(inst) ? undefined : true"
          :class="['griddle-tile', {
            'griddle-resizing': resize?.instanceKey === inst.key,
            'griddle-selected': editable && isBase(inst) && selection.has(inst.tile.id),
          }]"
          :style="instanceStyle(inst)"
          :ref="(el) => registerNode(inst.key, el as HTMLDivElement | null)"
          @pointerdown="(e) => onTilePointerDown(e, inst)"
        >
          <slot name="tile" :tile="inst.tile" :selected="editable && isBase(inst) && selection.has(inst.tile.id)" />
          <template v-if="editable && isBase(inst) && inst.tile.resizable !== false">
            <div
              v-for="c in tileHandles(inst.tile)"
              :key="c"
              :data-griddle-handle="c"
              :style="handleStyle(c)"
              @pointerdown="(e) => onResizeHandleDown(e, inst, c)"
            ></div>
          </template>
        </div>
      </template>
      <div
        v-if="drag && draggedTile"
        :data-griddle-tile="draggedTile.id"
        class="griddle-tile griddle-dragging"
        :style="dragOverlayStyle"
      >
        <slot name="tile" :tile="draggedTile" :selected="selection.has(draggedTile.id)" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Loop-mode renderer ("object looping") — see @griddle/core loop.ts for the
// coordinate model. Mirrors the React GriddleLoopGrid: an overflow-hidden
// viewport, a transform-translated plane driven by an unbounded camera, and
// NO native scrolling (wheel deltas feed the camera directly).
import { computed, onBeforeUnmount, onMounted, ref, watch, nextTick } from 'vue';
import type { CameraState, CellPos, Corner, Tile } from '@griddle/core';
import {
  DragController,
  PanController,
  loopInstances,
  loopPeriod,
  resolveLoop,
} from '@griddle/core';
import type { LoopTileInstance } from '@griddle/core';
import type { GriddleApi } from './useGriddle.js';

const props = defineProps<{
  api: GriddleApi;
  className?: string;
  height?: number | string;
  showGrid?: boolean;
  selection?: Set<string>;
}>();

const emit = defineEmits<{
  (e: 'selectionChange', selection: Set<string>): void;
  (e: 'dragStart', tileId: string): void;
  (e: 'dragEnd', tileId: string, committed: boolean): void;
  (e: 'resizeStart', tileId: string): void;
  (e: 'resizeEnd', tileId: string, committed: boolean): void;
  (e: 'cameraChange', camera: CameraState): void;
}>();

const DEFAULT_DRAG_IGNORE = 'a, button, input, textarea, select, [contenteditable]';
const PAN_THRESHOLD_PX = 4;

const viewportEl = ref<HTMLDivElement | null>(null);
const planeEl = ref<HTMLDivElement | null>(null);

const config = computed(() => props.api.config.value);
const loop = computed(() => resolveLoop(config.value));
const editable = computed(() => loop.value?.interaction === 'edit');
const gap = computed(() => config.value.gap ?? 0);
const halfGap = computed(() => gap.value / 2);
const colSize = computed(() => config.value.unitWidth + gap.value);
const rowSize = computed(() => config.value.unitHeight + gap.value);
const period = computed(() => loopPeriod(config.value, props.api.tiles.value));

// ---- camera plumbing ------------------------------------------------------
const pan = new PanController();
watch(loop, (l) => {
  if (l) pan.setPhysics({ friction: l.friction, ease: l.ease, maxVelocity: l.maxVelocity });
}, { immediate: true });

const view = ref({ cxCell: 0, cyCell: 0, vw: 1000, vh: 800 });
let lastCam: CameraState | null = null;
let raf = 0;
let resizeObserver: ResizeObserver | null = null;

function onWheel(e: WheelEvent) {
  e.preventDefault();
  const k = e.deltaMode === 1 ? 16 : e.deltaMode === 2 ? 100 : 1;
  pan.scrollBy(e.deltaX * k, e.deltaY * k);
}

function frame(now: number) {
  raf = requestAnimationFrame(frame);
  const st = pan.tick(now);

  const plane = planeEl.value;
  if (plane) {
    plane.style.transform = `translate3d(${-st.x}px, ${-st.y}px, 0)`;
  }
  const el = viewportEl.value;
  if (el && props.showGrid !== false) {
    el.style.backgroundPosition = `${-st.x % colSize.value}px ${-st.y % rowSize.value}px`;
  }

  const cxCell = Math.floor(st.x / colSize.value);
  const cyCell = Math.floor(st.y / rowSize.value);
  const cur = view.value;
  if (cxCell !== cur.cxCell || cyCell !== cur.cyCell) {
    view.value = { ...cur, cxCell, cyCell };
  }

  if (
    !lastCam || lastCam.x !== st.x || lastCam.y !== st.y ||
    lastCam.isMoving !== st.isMoving || lastCam.isDragging !== st.isDragging
  ) {
    lastCam = st;
    emit('cameraChange', st);
  }
}

const instances = computed(() => {
  void props.api.version.value; // re-run on grid changes
  const bufX = 2 * colSize.value;
  const bufY = 2 * rowSize.value;
  return loopInstances(config.value, props.api.tiles.value, {
    x: view.value.cxCell * colSize.value - bufX,
    y: view.value.cyCell * rowSize.value - bufY,
    width: view.value.vw + colSize.value + 2 * bufX,
    height: view.value.vh + rowSize.value + 2 * bufY,
  });
});

// ---- pan gesture ----------------------------------------------------------
let panGesture: { pointerId: number; startX: number; startY: number; moved: boolean } | null = null;
let suppressClick = false;

function onContainerPointerDown(e: PointerEvent) {
  const onTile = !!(e.target as HTMLElement).closest('[data-griddle-tile]');
  if (editable.value && !onTile) setSelection(new Set());
  // Tiles that start drags stopPropagation, so reaching here from a tile
  // means it was not draggable — panning is the right fallback.
  if (!loop.value?.dragPan || e.button !== 0) return;
  const ignoreSelector = config.value.dragIgnoreFrom ?? DEFAULT_DRAG_IGNORE;
  if (ignoreSelector && (e.target as HTMLElement).closest(ignoreSelector)) return;
  panGesture = { pointerId: e.pointerId, startX: e.clientX, startY: e.clientY, moved: false };
}

function onClickCapture(e: MouseEvent) {
  if (suppressClick) {
    suppressClick = false;
    e.preventDefault();
    e.stopPropagation();
  }
}

// ---- selection ('edit' interaction) ---------------------------------------
const internalSelection = ref<Set<string>>(new Set());
const selection = computed(() => props.selection ?? internalSelection.value);
function setSelection(next: Set<string>) {
  if (!props.selection) internalSelection.value = next;
  emit('selectionChange', next);
}

// ---- tile drag / resize ('edit' interaction) ------------------------------
const dragController = new DragController(props.api.grid);

interface LoopDragVisual {
  tileId: string;
  instanceLeft: number;
  instanceTop: number;
  pickupCol: number;
  pickupRow: number;
  deltaX: number;
  deltaY: number;
  indicatorCol: number | null;
  indicatorRow: number | null;
}
const drag = ref<LoopDragVisual | null>(null);
let dragStartPointerX = 0;
let dragStartPointerY = 0;

interface LoopResizeState {
  tileId: string;
  instanceKey: string;
  instanceDx: number;
  instanceDy: number;
  corner: Corner;
  startPointerX: number;
  startPointerY: number;
  startW: number;
  startH: number;
  startCol: number;
  startRow: number;
  previewW: number;
  previewH: number;
  previewCol: number;
  previewRow: number;
}
const resize = ref<LoopResizeState | null>(null);

function syncTiles() {
  props.api.tiles.value = props.api.grid.tiles;
  props.api.version.value++;
}

function isBase(inst: LoopTileInstance): boolean {
  return inst.kx === 0 && inst.ky === 0;
}
function isGhost(inst: LoopTileInstance): boolean {
  return editable.value && !isBase(inst);
}

function onTilePointerDown(e: PointerEvent, inst: LoopTileInstance) {
  if (!editable.value) return; // pan mode: container pan handler takes it
  if (!isBase(inst)) return; // ghosts are display-only
  const tile = inst.tile;
  if (tile.draggable === false) return;
  if ((e.target as HTMLElement).dataset.griddleHandle) return;
  const ignoreSelector = config.value.dragIgnoreFrom ?? DEFAULT_DRAG_IGNORE;
  if (ignoreSelector && (e.target as HTMLElement).closest(ignoreSelector)) return;

  if (e.metaKey || e.ctrlKey) {
    e.preventDefault();
    const next = new Set(selection.value);
    if (next.has(tile.id)) next.delete(tile.id);
    else next.add(tile.id);
    setSelection(next);
    e.stopPropagation();
    return;
  }
  setSelection(new Set([tile.id]));

  // No pointer capture: the grabbed instance unmounts (drag renders as an
  // overlay), which would release the capture mid-gesture.
  if (!dragController.start(tile.id)) return;
  dragStartPointerX = e.clientX;
  dragStartPointerY = e.clientY;
  drag.value = {
    tileId: tile.id,
    instanceLeft: inst.left,
    instanceTop: inst.top,
    pickupCol: tile.col,
    pickupRow: tile.row,
    deltaX: 0,
    deltaY: 0,
    indicatorCol: tile.col,
    indicatorRow: tile.row,
  };
  emit('dragStart', tile.id);
  e.stopPropagation();
}

function onResizeHandleDown(e: PointerEvent, inst: LoopTileInstance, c: Corner) {
  if (!editable.value) return;
  const tile = inst.tile;
  if (tile.resizable === false) return;
  (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
  const baseLeft = tile.col * colSize.value + halfGap.value;
  const baseTop = tile.row * rowSize.value + halfGap.value;
  resize.value = {
    tileId: tile.id,
    instanceKey: inst.key,
    instanceDx: inst.left - baseLeft,
    instanceDy: inst.top - baseTop,
    corner: c,
    startPointerX: e.clientX,
    startPointerY: e.clientY,
    startW: tile.w,
    startH: tile.h,
    startCol: tile.col,
    startRow: tile.row,
    previewW: tile.w,
    previewH: tile.h,
    previewCol: tile.col,
    previewRow: tile.row,
  };
  emit('resizeStart', tile.id);
  e.stopPropagation();
}

function onPointerMove(e: PointerEvent) {
  if (panGesture && e.pointerId === panGesture.pointerId) {
    const now = performance.now();
    if (!panGesture.moved) {
      const dist = Math.hypot(e.clientX - panGesture.startX, e.clientY - panGesture.startY);
      if (dist >= PAN_THRESHOLD_PX) {
        panGesture.moved = true;
        pan.dragStart(panGesture.startX, panGesture.startY, now);
        pan.dragMove(e.clientX, e.clientY, now);
      }
    } else {
      pan.dragMove(e.clientX, e.clientY, now);
    }
    return;
  }

  const d = drag.value;
  if (d) {
    // Ghost edit: plain grid semantics in the base copy — no wrapping.
    const dx = e.clientX - dragStartPointerX;
    const dy = e.clientY - dragStartPointerY;
    const candidate: CellPos = {
      col: d.pickupCol + Math.round(dx / colSize.value),
      row: d.pickupRow + Math.round(dy / rowSize.value),
    };
    const result = dragController.update(candidate);
    drag.value = {
      ...d,
      deltaX: dx,
      deltaY: dy,
      indicatorCol: result.indicatorCell ? result.indicatorCell.col : null,
      indicatorRow: result.indicatorCell ? result.indicatorCell.row : null,
    };
    if (result.changed) syncTiles();
  }

  const r = resize.value;
  if (r) {
    const dx = e.clientX - r.startPointerX;
    const dy = e.clientY - r.startPointerY;
    let dw = 0, dh = 0, dcol = 0, drow = 0;
    const stepsX = Math.round(dx / colSize.value);
    const stepsY = Math.round(dy / rowSize.value);
    if (r.corner === 'se' || r.corner === 'ne') dw = stepsX;
    if (r.corner === 'se' || r.corner === 'sw') dh = stepsY;
    if (r.corner === 'sw' || r.corner === 'nw') { dw = -stepsX; dcol = stepsX; }
    if (r.corner === 'ne' || r.corner === 'nw') { dh = -stepsY; drow = stepsY; }
    const tile = props.api.grid.getTile(r.tileId);
    const minW = tile?.minW ?? 1;
    const minH = tile?.minH ?? 1;
    const maxW = Math.min(tile?.maxW ?? Infinity, config.value.cols);
    const maxH = Math.min(tile?.maxH ?? Infinity, config.value.rows);
    const nW = Math.min(maxW, Math.max(minW, r.startW + dw));
    const nH = Math.min(maxH, Math.max(minH, r.startH + dh));
    const nC = r.startCol + dcol;
    const nR = r.startRow + drow;
    if (nW !== r.previewW || nH !== r.previewH || nC !== r.previewCol || nR !== r.previewRow) {
      resize.value = { ...r, previewW: nW, previewH: nH, previewCol: nC, previewRow: nR };
    }
  }
}

function onPointerUp(e: PointerEvent) {
  if (panGesture && e.pointerId === panGesture.pointerId) {
    if (panGesture.moved) {
      pan.dragEnd(performance.now());
      suppressClick = true;
    }
    panGesture = null;
    return;
  }

  if (drag.value) {
    const tileId = drag.value.tileId;
    const { committed } = dragController.end();
    drag.value = null;
    syncTiles();
    emit('dragEnd', tileId, committed);
  }
  const r = resize.value;
  if (r) {
    const t = props.api.grid.getTile(r.tileId);
    let committed = false;
    if (t) {
      const target = { col: r.previewCol, row: r.previewRow };
      if (target.col !== t.col || target.row !== t.row) {
        props.api.moveTile(r.tileId, target);
      }
      if (r.previewW !== t.w || r.previewH !== t.h) {
        committed = props.api.resizeTile(r.tileId, { w: r.previewW, h: r.previewH });
      } else {
        committed = r.previewCol !== r.startCol || r.previewRow !== r.startRow
          || r.previewW !== r.startW || r.previewH !== r.startH;
      }
    }
    resize.value = null;
    emit('resizeEnd', r.tileId, committed);
  }
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape' && editable.value) setSelection(new Set());
}

onMounted(() => {
  const el = viewportEl.value;
  if (el) {
    el.addEventListener('wheel', onWheel, { passive: false });
    const measure = () => {
      const cur = view.value;
      if (el.clientWidth !== cur.vw || el.clientHeight !== cur.vh) {
        view.value = { ...cur, vw: el.clientWidth, vh: el.clientHeight };
      }
    };
    measure();
    resizeObserver = new ResizeObserver(measure);
    resizeObserver.observe(el);
  }
  raf = requestAnimationFrame(frame);
  window.addEventListener('pointermove', onPointerMove);
  window.addEventListener('pointerup', onPointerUp);
  window.addEventListener('pointercancel', onPointerUp);
  window.addEventListener('keydown', onKeyDown);
});
onBeforeUnmount(() => {
  cancelAnimationFrame(raf);
  viewportEl.value?.removeEventListener('wheel', onWheel);
  resizeObserver?.disconnect();
  window.removeEventListener('pointermove', onPointerMove);
  window.removeEventListener('pointerup', onPointerUp);
  window.removeEventListener('pointercancel', onPointerUp);
  window.removeEventListener('keydown', onKeyDown);
});

// ---- FLIP for edit-mode repacks (keyed by world key) ----------------------
const tileNodes = new Map<string, HTMLDivElement>();
const prevRects = new Map<string, { x: number; y: number }>();
function registerNode(key: string, el: HTMLDivElement | null) {
  if (el) tileNodes.set(key, el);
  else tileNodes.delete(key);
}

watch(() => props.api.version.value, async () => {
  await nextTick();
  const draggerId = drag.value?.tileId ?? null;
  const seen = new Set<string>();
  for (const inst of instances.value) {
    const key = inst.key;
    seen.add(key);
    const x = inst.left;
    const y = inst.top;
    if (editable.value && inst.tile.id !== draggerId) {
      const p = prevRects.get(key);
      const node = tileNodes.get(key);
      if (p && node) {
        const dx = p.x - x;
        const dy = p.y - y;
        if (
          (dx !== 0 || dy !== 0) &&
          Math.abs(dx) < period.value.width / 2 &&
          Math.abs(dy) < period.value.height / 2
        ) {
          node.style.transition = 'none';
          node.style.transform = `translate(${dx}px, ${dy}px)`;
          requestAnimationFrame(() => {
            node.style.transition = 'transform 220ms cubic-bezier(.2,.7,.2,1)';
            node.style.transform = 'translate(0,0)';
          });
        }
      }
    }
    prevRects.set(key, { x, y });
  }
  for (const key of prevRects.keys()) {
    if (!seen.has(key)) prevRects.delete(key);
  }
});

// ---- styles ----------------------------------------------------------------
const viewportStyle = computed(() => {
  const showGrid = props.showGrid !== false;
  const bg = showGrid
    ? {
        backgroundImage: `linear-gradient(to right, rgba(0,0,0,0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,0,0,0.08) 1px, transparent 1px)`,
        backgroundSize: `${colSize.value}px ${rowSize.value}px`,
        backgroundPosition: '0 0',
      }
    : {};
  return {
    position: 'relative' as const,
    overflow: 'hidden' as const,
    height: typeof props.height === 'number' ? props.height + 'px' : (props.height ?? '100%'),
    touchAction: 'none' as const,
    userSelect: 'none' as const,
    cursor: !editable.value && loop.value?.dragPan ? 'grab' : undefined,
    ['--griddle-tile-radius' as string]: (config.value.tileRadius ?? 4) + 'px',
    ...bg,
  };
});

const planeStyle = computed(() => ({
  position: 'absolute' as const,
  top: '0',
  left: '0',
  width: '0',
  height: '0',
  willChange: 'transform',
}));

function instanceStyle(inst: LoopTileInstance) {
  const r = resize.value;
  const isResizingInst = r?.instanceKey === inst.key;
  let left = inst.left;
  let top = inst.top;
  let width = inst.width;
  let heightPx = inst.height;
  if (isResizingInst && r) {
    left = r.previewCol * colSize.value + halfGap.value + r.instanceDx;
    top = r.previewRow * rowSize.value + halfGap.value + r.instanceDy;
    width = r.previewW * config.value.unitWidth + (r.previewW - 1) * gap.value;
    heightPx = r.previewH * config.value.unitHeight + (r.previewH - 1) * gap.value;
  }
  const ghost = isGhost(inst);
  const isSelected = editable.value && isBase(inst) && selection.value.has(inst.tile.id);
  return {
    position: 'absolute' as const,
    left: left + 'px',
    top: top + 'px',
    width: width + 'px',
    height: heightPx + 'px',
    boxSizing: 'border-box' as const,
    cursor: editable.value && isBase(inst) ? 'grab' : undefined,
    userSelect: 'none' as const,
    // Ghosts are display-only: pointer-transparent (so the gesture falls
    // through to drag-pan) and dimmed to mark the editable copy.
    pointerEvents: ghost ? ('none' as const) : undefined,
    zIndex: isResizingInst ? 10 : 1,
    opacity: isResizingInst ? 0.85 : ghost ? 0.55 : 1,
    boxShadow: isSelected
      ? '0 0 0 3px rgba(59, 91, 219, 0.85), inset 0 0 0 1px rgba(59, 91, 219, 0.3)'
      : '',
    borderRadius: (config.value.tileRadius ?? 4) + 'px',
  };
}

const draggedTile = computed<Tile | null>(() =>
  drag.value ? props.api.grid.getTile(drag.value.tileId) ?? null : null,
);

const dragOverlayStyle = computed(() => {
  const d = drag.value;
  const t = draggedTile.value;
  if (!d || !t) return {};
  return {
    position: 'absolute' as const,
    left: d.instanceLeft + 'px',
    top: d.instanceTop + 'px',
    width: t.w * config.value.unitWidth + (t.w - 1) * gap.value + 'px',
    height: t.h * config.value.unitHeight + (t.h - 1) * gap.value + 'px',
    boxSizing: 'border-box' as const,
    cursor: 'grabbing',
    userSelect: 'none' as const,
    zIndex: 20,
    opacity: 0.85,
    transform: `translate(${d.deltaX}px, ${d.deltaY}px)`,
    filter: 'drop-shadow(0 8px 16px rgba(0,0,0,0.18))',
    borderRadius: (config.value.tileRadius ?? 4) + 'px',
    pointerEvents: 'none' as const,
  };
});

// Drop indicator: rendered in the base copy (ghost edit is plain-grid).
const indicatorRect = computed(() => {
  const d = drag.value;
  if (!d || d.indicatorCol === null || d.indicatorRow === null) return null;
  const t = props.api.grid.getTile(d.tileId);
  if (!t) return null;
  return {
    left: d.indicatorCol * colSize.value + halfGap.value,
    top: d.indicatorRow * rowSize.value + halfGap.value,
    width: t.w * config.value.unitWidth + (t.w - 1) * gap.value,
    height: t.h * config.value.unitHeight + (t.h - 1) * gap.value,
  };
});

function tileHandles(tile: Tile): Corner[] {
  return tile.resizeHandles ?? config.value.resizeHandles ?? ['se'];
}

function handleStyle(c: Corner) {
  const size = 12;
  const base = {
    position: 'absolute' as const,
    width: size + 'px',
    height: size + 'px',
    background: 'rgba(60,60,60,0.7)',
    border: '2px solid white',
    borderRadius: '3px',
    cursor: `${c}-resize`,
    touchAction: 'none' as const,
  } as Record<string, unknown>;
  if (c === 'nw') return { ...base, top: -size / 2 + 'px', left: -size / 2 + 'px' };
  if (c === 'ne') return { ...base, top: -size / 2 + 'px', right: -size / 2 + 'px' };
  if (c === 'sw') return { ...base, bottom: -size / 2 + 'px', left: -size / 2 + 'px' };
  return { ...base, bottom: -size / 2 + 'px', right: -size / 2 + 'px' };
}

const className = computed(() => props.className ?? '');
</script>
